### ISSUE TITLE
Oracle Java

### ISSUE THREAD

**Issue by mtarbox** [aryonp/unifi#2]
Oracle changed their policies. 
The Oracle JDK License has changed for releases starting April 16, 2019.

The new Oracle Technology Network License Agreement for Oracle Java SE is substantially different from prior Oracle JDK licenses. The new license permits certain uses, such as personal use and development use, at no cost -- but other uses authorized under prior Oracle JDK licenses may no longer be available. Please review the terms carefully before downloading and using this product. An FAQ is available here: https://www.oracle.com/technetwork/java/javase/overview/oracle-jdk-faqs.html

Oracle Java downloads now require logging in to an Oracle account to download Java updates, like the latest Oracle Java 8u211 / Java SE 8u212. Because of this I cannot update the PPA with the latest Java (and the old links were broken by Oracle).

For this reason, THIS PPA IS DISCONTINUED (unless I find some way around this limitation).

Oracle Java (JDK) Installer (automatically downloads and installs Oracle JDK8). There are no actual Java files in this PPA.

Important -> Why Oracle Java 7 And 6 Installers No Longer Work: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

Update: Oracle Java 9 has reached end of life: http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

The PPA supports Ubuntu 18.10, 18.04, 16.04, 14.04 and 12.04.

More info (and Ubuntu installation instructions):
- http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

Debian installation instructions:
- Oracle Java 8: http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

For Oracle Java 11, see a different PPA -> https://www.linuxuprising.com/2018/10/how-to-install-oracle-java-11-in-ubuntu.html

**Comment by businessBoris** [comment]
Don't use Oracle Java. 
https://www.technologist.site/2016/06/02/how-to-install-ubiquiti-unifi-controller-5-on-the-raspberry-pi/2/ using the comments by Richard in preference to the main text where they differ.
My controller has been happily running on an Odroid XU4 for some months - just discovered Ubiquiti.

Hope this helps.

**Comment by mtarbox** [comment]
I installed openjdk and it worked, after reaching out to the unifi forums. AmazedMender16 assisted. Worked like a champ.
Thanks for reaching out.

**Comment by businessBoris** [comment]
Whenever I see Oracle mentioned, I always look for an alternative. 
Glad you're satiated!
Perhaps you would consider closing the issue for @aryonp .

**Comment by mtarbox** [comment]
@aryonp thank you, as well as @businessBoris
